name       : libmtp
version    : 1.1.13
release    : 3
source     :
    - https://kent.dl.sourceforge.net/project/libmtp/libmtp/1.1.13/libmtp-1.1.13.tar.gz : 494ee02fbfbc316aad75b93263dac00f02a4899f28cfda1decbbd6e26fda6d40
license    : LGPL-2.1
component  : desktop.library
summary    : Library implementation of the Media Transfer Protocol
description: |
    Library implementation of the Media Transfer Protocol
builddeps  :
    - pkgconfig(libusb-1.0)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
