name       : libmtp
version    : 1.1.16
release    : 7
source     :
    - https://kent.dl.sourceforge.net/project/libmtp/libmtp/1.1.16/libmtp-1.1.16.tar.gz : 5b68f9dd1ed38de558de687f40e255a39e4d5e32ef3de601f0ac19dd5682bba0
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Library implementation of the Media Transfer Protocol
description: |
    This package provides a software library for communicating with MTP
    (Media Transfer Protocol) media players, typically audio players, video
    players, smartphones, etc.
builddeps  :
    - pkgconfig(libusb-1.0)
    - libgcrypt-devel
setup      : |
    %configure --disable-static \
               --with-udev=%libdir%/udev
build      : |
    %make
install    : |
    %make_install
