name       : libmtp
version    : 1.1.15
release    : 5
source     :
    - https://kent.dl.sourceforge.net/project/libmtp/libmtp/1.1.15/libmtp-1.1.15.tar.gz : d040900b46757e311b1fb3bfa8c05db09c8b6811e044bce8c88c9f3f6d3a3021
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Library implementation of the Media Transfer Protocol
description: |
    This package provides a software library for communicating with MTP
    (Media Transfer Protocol) media players, typically audio players, video
    players, smartphones, etc.
builddeps  :
    - pkgconfig(libusb-1.0)
setup      : |
    %configure --disable-static \
               --with-udev=%libdir%/udev
build      : |
    %make
install    : |
    %make_install
