name       : libmtp
version    : 1.1.12
release    : 2
source     :
    - https://kent.dl.sourceforge.net/project/libmtp/libmtp/1.1.12/libmtp-1.1.12.tar.gz : cdf59e816c6cda3e908a876c7fb42943f40b85669aea0029a1ca431c89afa1a0
license    : LGPL-2.1
component  : desktop.library
summary    : Library implementation of the Media Transfer Protocol
description: |
    Library implementation of the Media Transfer Protocol
builddeps  :
    - pkgconfig(libusb-1.0)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
