name       : libmtp
version    : 1.1.14
release    : 4
source     :
    - https://kent.dl.sourceforge.net/project/libmtp/libmtp/1.1.14/libmtp-1.1.14.tar.gz : 3817d3e296be8f1bc527385585780e70984e8e0d6a0d00349240d67e3df412e8
license    : LGPL-2.1
component  : desktop.library
summary    : Library implementation of the Media Transfer Protocol
description: |
    This package provides a software library for communicating with MTP
    (Media Transfer Protocol) media players, typically audio players, video
    players, smartphones, etc.
builddeps  :
    - pkgconfig(libusb-1.0)
setup      : |
    %configure --disable-static \
               --with-udev=%libdir%/udev
build      : |
    %make
install    : |
    %make_install
