name       : libmtp
version    : 1.1.17
release    : 8
source     :
    - https://sourceforge.net/projects/libmtp/files/libmtp/1.1.17/libmtp-1.1.17.tar.gz : f8a34cf52d9f9b9cb8c7f26b12da347d4af7eb904c13189602e4c6b62d1a79dc
homepage   : http://libmtp.sourceforge.net/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Library implementation of the Media Transfer Protocol
description: |
    This package provides a software library for communicating with MTP
    (Media Transfer Protocol) media players, typically audio players, video
    players, smartphones, etc.
builddeps  :
    - pkgconfig(libgcrypt)
    - pkgconfig(libusb-1.0)
setup      : |
    %configure --disable-static \
               --with-udev=%libdir%/udev
build      : |
    %make
install    : |
    %make_install
