name       : libmtp
version    : 1.1.9
release    : 1
source     :
    - http://softlayer-sng.dl.sourceforge.net/project/libmtp/libmtp/1.1.9/libmtp-1.1.9.tar.gz : 23f1d3c0b54107388bf2824d56415e9e087c980c86e5d179865652c022b6b189
license    : LGPL-2.1
summary    : Library implementation of the Media Transfer Protocol
description: |
    Library implementation of the Media Transfer Protocol
builddeps  :
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
